name: application_rano
publish_to: "Apk pour les agents de terrain de Eatc." # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: any
  bcrypt: ^1.1.3
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  intl: ^0.19.0
  get: ^4.6.6
  dropdown_button2: ^2.3.9
  sa4_migration_kit: ^1.0.0
  simple_animations: ^5.0.2
  supercharged: ^2.1.1
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  pin_code_fields: ^8.0.1
  provider: ^6.1.2
  flutter_bloc: ^8.1.4
  flutter_native_splash: ^2.3.10
  image_picker: ^1.0.7

  sqflite: ^2.3.2
  permission_handler: ^11.3.0
  path: ^1.9.0
  connectivity: ^3.0.6
  meta: ^1.11.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  moor: ^4.6.1+1
  moor_flutter: ^4.1.0
  flutter_lints: ^3.0.1
  path_provider: ^2.1.2
  bloc: any
  syncfusion_flutter_datepicker: ^25.2.4
  flutter_image_compress: any
  image: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
